### ISSUE TITLE
Does it modify stylesheets?

### ISSUE THREAD

**Issue by trusktr** [davidkpiano/RxCSS#3]
From what I can tell from the README, it seems like this modifies stylesheets?

Just curious because it seems a little heavy to be animating stylesheets compared to animating styles directly via `style` attributes.

I suppose typed-css will make this all smoother. Is that out yet?

**Comment by davidkpiano** [comment]
> it seems like this modifies stylesheets?

Nope, it does not modify actual stylesheets. It simply sets the CSS variables using JS.

**Comment by trusktr** [comment]
How does that work, can you give a small example of how to modify a CSS variable?

**Comment by davidkpiano** [comment]
Sure, I have a few slides on it here: http://slides.com/davidkhourshid/reactanim#/18

**Comment by rgbkrk** [comment]
This still changes styles using attributes on `style`, using `setProperty`:

```js
element.style
  .setProperty('--my-color', 'rebeccapurple');

element.style
  .getPropertyValue('--my-color');
// => 'rebeccapurple'

element.style
  .removeProperty('--my-color');
```

To modify the CSS variables defined on the `:root`:

```js
const root = document.querySelector(':root');
root.style.setProperty('--my-color', 'green');
```

**Comment by davidkpiano** [comment]
@rgbkrk Right, and RxCSS will modify the CSS variables on the root. It uses `document.documentElement` which is equivalent to `document.querySelector(':root')`.

**Comment by rgbkrk** [comment]
TIL, thanks!
