### ISSUE TITLE
easy to use bundle, Plnkr example

### ISSUE THREAD

**Issue by niklas-dahl** [davidkpiano/RxCSS#4]
I really want to play with this so it would be awesome if you could provide a bundle that you can just import via a script tag without a build step.

Just importing this without a bundler throws `Uncaught ReferenceError: require is not defined`
```
  <script src="https://unpkg.com/@reactivex/rxjs/dist/global/Rx.js"></script>
  <script src="https://unpkg.com/rxcss@latest"></script>
```

Would be cool if this could work in plunkr.

Thanks.

**Comment by davidkpiano** [comment]
Fixed the README.md to point to the correct minified file:

```html
<script src="https://unpkg.com/@reactivex/rxjs/dist/global/Rx.min.js"></script>
<script src="https://unpkg.com/rxcss@latest/dist/rxcss.min.js"></script>
```
